/**
 * API Product-Composite
 *
 * Contact: soporte@miempresa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReviewSummaryDto { 
    reviewId?: number;
    author?: string;
    subject?: string;
    content?: string;
}

