/**
 * API Product-Composite
 *
 * Contact: soporte@miempresa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ServiceAddressesDto { 
    cmp?: string;
    pro?: string;
    rev?: string;
    rec?: string;
}

